let appData = loadData();
let charts = {};
const AED = new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED'});
const today = new Date().toISOString().slice(0,10);
const currentMonth = today.slice(0,7);
const screens = {
  dashboard:['Dashboard','Your money position, risks, goals and monthly control.'],
  transactions:['Transactions','Track daily income, expenses and transfers.'],
  budget:['Budget','Plan monthly spending and compare planned vs actual.'],
  accounts:['Accounts','Bank accounts, cash wallets and balances.'],
  cards:['Credit Cards','Outstanding, limits, utilization and due dates.'],
  loans:['Loans & Debts','Bank loans, personal debts, EMI and debt progress.'],
  bills:['Utility Bills','Recurring bills, due dates and payment status.'],
  goals:['Goals','Emergency fund, car fund, land fund and medical fund.'],
  reports:['Reports','Monthly financial analysis and spending patterns.'],
  sync:['Google Drive Sync','Backup and restore design. Live Google sync will be Phase 3.']
};
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function money(v){return AED.format(Number(v||0))}
function sum(arr,field){return arr.reduce((a,b)=>a+Number(b[field]||0),0)}
function monthMatch(x){return String(x.date||x.month||'').slice(0,7)===currentMonth}
function add(type,form){const r=Object.fromEntries(new FormData(form).entries());r.id=uid();appData[type].push(r);saveData();form.reset();renderAll()}
function del(type,id){appData[type]=appData[type].filter(x=>x.id!==id);saveData();renderAll()}
function switchScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));document.getElementById('screenTitle').textContent=screens[id][0];document.getElementById('screenSubtitle').textContent=screens[id][1]}
document.querySelectorAll('.nav button').forEach(btn=>btn.onclick=()=>switchScreen(btn.dataset.screen));
document.getElementById('exportBtn').onclick=exportFinanceData;document.getElementById('importFile').onchange=e=>e.target.files[0]&&importFinanceData(e.target.files[0]);document.getElementById('resetBtn').onclick=()=>{if(confirm('Delete all data from this browser?')){appData=structuredClone(defaultFinanceData);saveData();renderAll()}};
function metric(label,value,note,cls='blue'){return `<div class="card metric"><small>${label}</small><h3 class="${cls}">${value}</h3><p>${note}</p></div>`}
function chart(id,type,labels,data){if(charts[id])charts[id].destroy();const el=document.getElementById(id);if(!el)return;charts[id]=new Chart(el,{type,data:{labels,datasets:[{data,borderWidth:1}]},options:{plugins:{legend:{position:'bottom'}},responsive:true}})}
function table(type,fields){const rows=appData[type];if(!rows.length)return '<div class="empty">No records yet.</div>';return `<div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th>${label(f)}</th>`).join('')}<th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr>${fields.map(f=>`<td>${isMoney(f)?money(r[f]):(r[f]||'-')}</td>`).join('')}<td><button class="btn danger" onclick="del('${type}','${r.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function label(s){return s.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}function isMoney(f){return ['amount','balance','limit','outstanding','minPayment','principal','emi','target','saved'].includes(f)}
function renderDashboard(){const assets=sum(appData.accounts,'balance')+sum(appData.goals,'saved');const cardDebt=sum(appData.cards,'outstanding');const loanDebt=sum(appData.loans,'outstanding');const liabilities=cardDebt+loanDebt;const income=sum(appData.transactions.filter(x=>monthMatch(x)&&x.type==='Income'),'amount');const expenses=sum(appData.transactions.filter(x=>monthMatch(x)&&x.type==='Expense'),'amount');const saving=income-expenses;const rate=income?Math.round((saving/income)*100):0;document.getElementById('dashboard').innerHTML=`<div class="grid grid-4">${metric('Net Worth',money(assets-liabilities),'Assets minus liabilities',(assets-liabilities)>=0?'good':'bad')}${metric('Assets',money(assets),'Accounts plus goal savings','blue')}${metric('Liabilities',money(liabilities),'Cards plus loans','bad')}${metric('Saving Rate',rate+'%','This month cash discipline',rate>=20?'good':'warn')}</div><div class="grid grid-2" style="margin-top:18px"><div class="card"><h3>Cash Flow</h3><canvas id="cashChart"></canvas></div><div class="card"><h3>Expense Categories</h3><canvas id="catChart"></canvas></div></div><div class="grid grid-3" style="margin-top:18px"><div class="card"><h3>Budget Control</h3>${budgetProgress()}</div><div class="card"><h3>Upcoming Bills</h3>${list(appData.bills.filter(x=>x.status!=='Paid').slice(0,5),'amount')}</div><div class="card"><h3>Goal Progress</h3>${goalProgress()}</div></div>`;chart('cashChart','bar',['Income','Expense','Saving'],[income,expenses,saving]);const cats={};appData.transactions.filter(x=>monthMatch(x)&&x.type==='Expense').forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount||0));chart('catChart','doughnut',Object.keys(cats),Object.values(cats))}
function budgetProgress(){if(!appData.budgets.length)return '<div class="empty">Add budget categories.</div>';return appData.budgets.map(b=>{const spent=sum(appData.transactions.filter(t=>monthMatch(t)&&t.type==='Expense'&&t.category===b.category),'amount');const pct=Number(b.amount)?Math.min(100,Math.round(spent/Number(b.amount)*100)):0;return `<p><b>${b.category}</b><span style="float:right">${money(spent)} / ${money(b.amount)}</span></p><div class="progress"><div style="width:${pct}%"></div></div>`}).join('')}
function goalProgress(){if(!appData.goals.length)return '<div class="empty">Add savings goals.</div>';return appData.goals.map(g=>{const pct=Number(g.target)?Math.min(100,Math.round(Number(g.saved||0)/Number(g.target)*100)):0;return `<p><b>${g.name}</b><span style="float:right">${pct}%</span></p><div class="progress"><div style="width:${pct}%"></div></div>`}).join('')}
function list(items,amountField){if(!items.length)return '<div class="empty">No records.</div>';return items.map(x=>`<div class="list-item"><span><b>${x.name||x.bank||x.category}</b><br><small>${x.dueDate||x.type||x.status||''}</small></span><b>${money(x[amountField]||x.outstanding||0)}</b></div>`).join('')}
function renderTransactions(){document.getElementById('transactions').innerHTML=`<div class="card"><form onsubmit="event.preventDefault();add('transactions',this)"><input name="date" type="date" value="${today}" required><select name="type"><option>Expense</option><option>Income</option><option>Transfer</option></select><input name="category" placeholder="Category" required><input name="subcategory" placeholder="Subcategory"><input name="account" placeholder="Account/Card"><input name="amount" type="number" step="0.01" placeholder="Amount" required><input name="tags" placeholder="Tags"><input name="note" placeholder="Note"><button class="btn primary">Add</button></form>${table('transactions',['date','type','category','subcategory','account','amount','tags','note'])}</div>`}
function renderBudget(){document.getElementById('budget').innerHTML=`<div class="card"><form onsubmit="event.preventDefault();add('budgets',this)"><input name="month" type="month" value="${currentMonth}" required><input name="category" placeholder="Category" required><input name="amount" type="number" step="0.01" placeholder="Planned Amount" required><select name="priority"><option>Essential</option><option>Important</option><option>Lifestyle</option><option>Luxury</option></select><button class="btn primary">Add</button></form>${table('budgets',['month','category','amount','priority'])}</div>`}
function renderAccounts(){document.getElementById('accounts').innerHTML=`<div class="card"><form onsubmit="event.preventDefault();add('accounts',this)"><input name="bank" placeholder="Bank / Wallet" required><select name="type"><option>Current</option><option>Savings</option><option>Cash</option><option>Wallet</option></select><select name="currency"><option>AED</option><option>LKR</option><option>USD</option></select><input name="balance" type="number" step="0.01" placeholder="Balance" required><button class="btn primary">Add</button></form>${table('accounts',['bank','type','currency','balance'])}</div>`}
function renderCards(){document.getElementById('cards').innerHTML=`<div class="card"><form onsubmit="event.preventDefault();add('cards',this)"><input name="bank" placeholder="Card Name" required><input name="limit" type="number" step="0.01" placeholder="Limit"><input name="outstanding" type="number" step="0.01" placeholder="Outstanding" required><input name="dueDate" type="date"><input name="minPayment" type="number" step="0.01" placeholder="Minimum Payment"><select name="status"><option>Active</option><option>Paid</option><option>Blocked</option></select><button class="btn primary">Add</button></form>${table('cards',['bank','limit','outstanding','dueDate','minPayment','status'])}</div>`}
function renderLoans(){document.getElementById('loans').innerHTML=`<div class="card"><form onsubmit="event.preventDefault();add('loans',this)"><input name="name" placeholder="Loan/Debt Name" required><select name="type"><option>Bank Loan</option><option>Personal Debt</option><option>Family Debt</option></select><input name="principal" type="number" step="0.01" placeholder="Original Amount"><input name="outstanding" type="number" step="0.01" placeholder="Outstanding" required><input name="emi" type="number" step="0.01" placeholder="Monthly EMI"><input name="endDate" type="date"><button class="btn primary">Add</button></form>${table('loans',['name','type','principal','outstanding','emi','endDate'])}</div>`}
function renderBills(){document.getElementById('bills').innerHTML=`<div class="card"><form onsubmit="event.preventDefault();add('bills',this)"><input name="name" placeholder="Bill Name" required><input name="amount" type="number" step="0.01" placeholder="Amount" required><input name="dueDate" type="date" required><select name="frequency"><option>Monthly</option><option>Quarterly</option><option>Yearly</option><option>One-time</option></select><select name="status"><option>Pending</option><option>Paid</option><option>Overdue</option></select><button class="btn primary">Add</button></form>${table('bills',['name','amount','dueDate','frequency','status'])}</div>`}
function renderGoals(){document.getElementById('goals').innerHTML=`<div class="card"><form onsubmit="event.preventDefault();add('goals',this)"><input name="name" placeholder="Goal Name" required><input name="target" type="number" step="0.01" placeholder="Target Amount" required><input name="saved" type="number" step="0.01" placeholder="Saved Amount"><input name="targetDate" type="date"><select name="type"><option>Emergency Fund</option><option>Debt Free</option><option>Car Fund</option><option>Land Fund</option><option>Medical Fund</option><option>Custom</option></select><button class="btn primary">Add</button></form>${table('goals',['name','type','target','saved','targetDate'])}</div>`}
function renderReports(){const income=sum(appData.transactions.filter(x=>monthMatch(x)&&x.type==='Income'),'amount');const expenses=sum(appData.transactions.filter(x=>monthMatch(x)&&x.type==='Expense'),'amount');document.getElementById('reports').innerHTML=`<div class="grid grid-3">${metric('Monthly Income',money(income),'Current month','good')}${metric('Monthly Expenses',money(expenses),'Current month','bad')}${metric('Free Cash Flow',money(income-expenses),'Income minus expenses',(income-expenses)>=0?'good':'bad')}</div><div class="card" style="margin-top:18px"><h3>Monthly Trend</h3><canvas id="reportChart"></canvas></div>`;chart('reportChart','line',['Income','Expense','Free Cash'],[income,expenses,income-expenses])}
function renderSync(){document.getElementById('sync').innerHTML=`<div class="card"><h3>Google Drive Sync - Phase 3</h3><p>This version has safe local storage plus manual backup/import. Google Drive automatic sync needs Google Cloud OAuth setup, Client ID and Drive API permission.</p><p><b>Current safe method:</b> use Export Backup and upload the JSON file to your Google Drive manually.</p><button class="btn primary" onclick="exportFinanceData()">Create Backup File</button></div>`}
function renderHealthScore(){const income=sum(appData.transactions.filter(x=>monthMatch(x)&&x.type==='Income'),'amount');const expenses=sum(appData.transactions.filter(x=>monthMatch(x)&&x.type==='Expense'),'amount');const assets=sum(appData.accounts,'balance');const debts=sum(appData.cards,'outstanding')+sum(appData.loans,'outstanding');const savingRate=income?Math.max(0,(income-expenses)/income):0;const emergency=expenses?Math.min(1,assets/(expenses*3)):0;return Math.round(savingRate*40+(1-Math.min(1,debts/Math.max(1,assets)))*30+emergency*30)}
function renderAll(){renderDashboard();renderTransactions();renderBudget();renderAccounts();renderCards();renderLoans();renderBills();renderGoals();renderReports();renderSync()}
renderAll();
